### PR TITLE
Deploying the portofolio website freely using the GitHub pages tool

### PR DESCRIPTION
**Pull request by jodrack07**
For this practical session, I learned to deploy my portfolio website using the GitHub pages tool to let people visit it online.

-Since I deploy this project before, I realized that some images and icons were not showing up, and I tried to fix the issue.
-To see the **live demo** check the **Live Demo** heading from the README.md file or just click [here](https://joseph07-drack.github.io/Portofolio/).

### CODE REVIEW

**Review by andersonlebon — CHANGES_REQUESTED** [review]
## Hi @joseph07-drack 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

almost-there
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Nice job 👏  👏  on deploying successfully your project however one of the requirements says that you should update your `READEME` file with a demo link. kindly let's go ahead and update the `README` file with the correct demo link. add this section 👇 
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jodrack07** [comment]
Oh!! I cannot imagine that I forgot to update the README file 🙂. 
Sorry about.

**Review by rustam-tolipov — APPROVED** [review]
## Hi @joseph07-drack 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

image

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by jodrack07** [comment]
Great ✔️.
Thanks for reviewing my project

**Pull request merged**
